export { default as Create } from "./Create"
export { default as Details } from "./Details"
export { default as Home } from "./Home"
export { default as About } from "./About"
export { default as Profile } from "./Profile"
export { default as Donate } from "./Donate"
